version: '3'

services:
  backend:
    image: be-teamstatsfoxs:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./src/main/resources:/app/src/main/resources
      - /opt/logs:/app/logs
