version: '3'
services:
  be-teamstatsfoxs:
    container_name: be-teamstatsfoxs
    image: be-teamstatsfoxs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/var/log
    ports:
      - "8090:8090"
    restart: always
