version: '3'
services:
  be-teamstatsfoxs:
    container_name: be-teamstatsfoxs
    image: be-teamstatsfoxs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/proyectos/teamstatsfoxs/images:/be-teamstatsfoxs/images
    ports:
      - "8090:8090"
    restart: always
